// <auto-generated/>
using System;
using System.Reflection;
using System.Resources;

[assembly: AssemblyVersionAttribute("2.0.5.0")]
[assembly: AssemblyFileVersionAttribute("2.0.5.0")]
[assembly: AssemblyConfigurationAttribute("Release")]
[assembly: AssemblyCompanyAttribute("Kent Boogaart")]
[assembly: AssemblyProductAttribute("The Helper Trinity")]
[assembly: AssemblyCopyrightAttribute("© Copyright. Kent Boogaart.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]
[assembly: CLSCompliantAttribute(true)]
[assembly: NeutralResourcesLanguageAttribute("en-US")]
[assembly: AssemblyInformationalVersionAttribute("2.0.5")]
